# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

source:      .
destination: ./_site
plugins:     []
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    America/New_York

future:      true
show_drafts: nil
limit_posts: 0

permalink:     date
paginate_path: 'page:num'

markdown:      Kramdown
markdown_ext:  markdown,mkd,mkdn,md

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

